"""add preprocessing and ocr metadata fields

Revision ID: 5d0f3501986a
Revises: 3a90138d10bf
Create Date: 2026-05-26 07:54:54.480345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0f3501986a'
down_revision = '3a90138d10bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_coordinates', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('bounding_boxes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('page_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preprocessed_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('preprocessing_options', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('preprocessing_options')
        batch_op.drop_column('preprocessed_path')
        batch_op.drop_column('page_metadata')
        batch_op.drop_column('bounding_boxes')
        batch_op.drop_column('ocr_coordinates')

    # ### end Alembic commands ###
